version: "3"
services:
  # hatedetectionserver:
  #   container_name: hateDetection
  #   build: ./hateDetection
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./hateDetection:/app
  #   restart: always

  react:
    container_name: react
    build: .
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
    restart: always
